# to parse cdhit files

cog_list = '/home/hermuba/bin/COGmapper/COG.list'
out = '/home/hermuba/data0118/cdhit/Escherichia0.70.COG_annotation'

import pandas as pd

def COG_to_df(cog_list, out):
    '''
    a function that merges COG_list provided by COG_mapper to translate eggNOG to 20 COGs
    input:
    - cog_list: COG.list provided by COGmapper
    - out: the output generated by COGmapper, with gene ID and COG1986

    output with df columns = ['gene ID', 'eggNOG', '20 COGs']
    '''

    # this data frame will contain COG.list
    cog = pd.DataFrame(columns = ['cog_category'])
    # this will contain gene ID v.s. eggNOG
    output = pd.DataFrame(columns = ['cog_ID'])

    with open(cog_list) as cog_list:
        for line in cog_list:
            # cog_list has some comments
            if '#' in line:
                pass
            else:

                category = line.split('\t')[0].replace('[', '').replace(']', '').replace('\ufeff', '') # [AE] or [A]
                ID = line.split('\t')[1].replace('\n', '') # COG0001
                cog.loc[ID, 'cog_category'] = category

    with open(out) as o:
        for line in o:
            gene_header = line.split('\t')[0]
            cog_ID = line.split('\t')[1].split('.')[1]
            output.loc[gene_header, 'cog_ID'] = cog_ID

    df = pd.merge(output, cog, left_on = 'cog_ID', right_index = True)

    return(df)
#df.to_pickle('\home\hermuba\resistantExp\EcoliGenomes\cdhitResult\ec0913_coganno_df')
